version: '3'
services:
  drupal:
    build: 
      context: './drupal'
    restart: 'always'
    ports:
      - '${DRUPAL_HTTP_PORT}:80'
    volumes:
      - '${APP_CODE_PATH_HOST}/modules:/var/www/html/modules'
      - '${APP_CODE_PATH_HOST}/sites:/var/www/html/sites'
      - '${APP_CODE_PATH_HOST}/profiles:/var/www/html/profiles'
      - '${APP_CODE_PATH_HOST}/themes:/var/www/html/themes'
  mysql:
    build:
      context: ./mysql
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}/mysql:/app'
      - '${MYSQL_PATH}/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    build: './phpmyadmin'
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'

