version: '3'
services:
  drupal:
    build:
      context: 'drupal'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_DRUPAL}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${DRUPAL_HOST_HTTP_PORT}:80'
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - ${MYSQL_PORT}:3306
volumes: {}
