FROM ghcr.io/deck-app/nginx:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY default.conf /etc/nginx/conf.d/default.conf
COPY default.conf /app/default.conf
RUN wget -O /var/preview/index.html https://raw.githubusercontent.com/deck-app/stack-preview-screen/main/install/index.html
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/nginx/conf.d/default.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www#g" /app/default.conf

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl

WORKDIR /var/www

COPY php_ini/php7.4.ini /etc/php7/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

RUN apk add php7-zip
RUN apk add zip php7-gd php7-pdo php7-pdo_dblib php7-pdo_mysql php7-pdo_odbc php7-pdo_pgsql php7-pdo_sqlite

COPY docker-entrypoint.sh /docker-entrypoint.sh
#DRUPAL_INSTALL enable or disable
ARG DRUPAL_INSTALL
RUN if [ ${DRUPAL_INSTALL} = true ]; then \
sed -i "s#{DRUPAL_INSTALL}#true#g" /docker-entrypoint.sh \
;else \
sed -i "s#{DRUPAL_INSTALL}#false#g" /docker-entrypoint.sh \
;fi

#Application Download
RUN curl -fLk -o /app/drupal.tar.gz  "https://www.drupal.org/download-latest/tar.gz"
RUN cd /app/ && tar -xzvf drupal.tar.gz && rm drupal.tar.gz

RUN chmod +x /docker-entrypoint.sh
CMD /docker-entrypoint.sh & /sbin/runit-wrapper