FROM ghcr.io/deck-app/apache:v7.4
LABEL maintainer Naba Das <hello@get-deck.com>

# Persistent runtime dependencies
# Example RUN apk add --no-cache php7-openssl php7-sysvmsg php7-curl

RUN mkdir -p /app
RUN mkdir -p /var/preview
COPY httpd.conf /etc/apache2/httpd.conf
COPY httpd.conf /app/httpd.conf
COPY preview/* /var/preview/
RUN sed -i "s#{SERVER_ROOT}#/var/preview#g" /etc/apache2/httpd.conf
RUN sed -i "s#{SERVER_ROOT}#/var/www#g" /app/httpd.conf

WORKDIR /var/www

COPY php_ini/php7.4.ini /etc/php7/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-pecl-xdebug \
&& echo "zend_extension=xdebug" >> /etc/php7/php.ini \
;fi

#Application Download
RUN curl -fLk -o /app/drupal.tar.gz  "https://www.drupal.org/download-latest/tar.gz"
RUN cd /app/ && tar -xzvf drupal.tar.gz && rm drupal.tar.gz

RUN apk add php7-zip php7-gd php7-pdo php7-pdo_dblib php7-pdo_mysql php7-pdo_odbc php7-pdo_pgsql php7-pdo_sqlite
RUN apk add zip

COPY docker-entrypoint.sh /docker-entrypoint.sh
#DRUPAL_INSTALL enable or disable
ARG DRUPAL_INSTALL
RUN if [ ${DRUPAL_INSTALL} = true ]; then \
sed -i "s#{DRUPAL_INSTALL}#true#g" /docker-entrypoint.sh \
;else \
sed -i "s#{DRUPAL_INSTALL}#false#g" /docker-entrypoint.sh \
;fi
RUN chmod +x /docker-entrypoint.sh
CMD /docker-entrypoint.sh & /sbin/runit-wrapper